/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Payment } from './Payment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PaymentService } from './Payment.service';
import { PaymentController } from './Payment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Payment])],
  providers: [PaymentService],
  exports: [PaymentService],
  controllers: [PaymentController],
})
export class PaymentModule {}
