import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PaymentCreate {
  @ApiProperty()
  payment_id: string;
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  payment_date: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  payment_method: string;
  @ApiProperty()
  status: string;
}

export class Payment {
  @ApiProperty()
  id: number;
  @ApiProperty()
  payment_id: string;
  @ApiProperty()
  invoice_number: string;
  @ApiProperty()
  payment_date: string;
  @ApiProperty()
  amount: string;
  @ApiProperty()
  payment_method: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
