/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Invoice } from './Invoice.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { InvoiceService } from './Invoice.service';
import { InvoiceController } from './Invoice.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Invoice])],
  providers: [InvoiceService],
  exports: [InvoiceService],
  controllers: [InvoiceController],
})
export class InvoiceModule {}
