/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Invoice, InvoiceCreate } from './dtos/Invoice.dto';
import { InvoiceController } from './Invoice.controller';
import { InvoiceService } from './Invoice.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('InvoiceController', () => {
  let controller: InvoiceController;
  let spyService: InvoiceService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: InvoiceService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [InvoiceController],
      providers: [InvoiceService, ApiServiceProvider],
    }).compile();

    controller = module.get<InvoiceController>(InvoiceController);
    spyService = module.get<InvoiceService>(InvoiceService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call InvoiceController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call InvoiceController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Invoice();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
